In [ ]:
#notebook 1 day_01_numpy_arsenal.ipynb


In [2]:
#Cell 1- importing numpy and creating arrays

#'import numpy as np' loads the Numpy libraries and givesit the nickname 'np'
#everytime i write something as np.something im using numpy
import numpy as np

#np.array() converrs a python list into a Numpy array
#a numpy array looks like a list but is stored in memory diffrently as a continous block - thats why it is so 
a = np.array([1, 2, 3, 4, 5])

#np.zeros((3, 4)) creates a matrix of 3 rows and 4 columns filled with 0.0
#uses zeros to initialize things before i put in the values
b = np.zeros((3, 4))

#np.ones((3, 4)) similarly will fill them with 1.0
#used ti initialize bias terms in neural networks
c = np.ones ((3,4))

#np.random.randn((3, 4)) we know that this will create a 3 by 4 matrix of random numbers
#they genrally tend to have a mean of 0 and a standard deviation of 1
#random values hellp the neurons in neural network to learn diffrent features
d = np.random.randn(3, 4)

#np.arange (0, 10, 0.5) is similar to python's range but for decimals
#here it will create values starting from 0 to the range stopping before 10 with steps as 0.5
# like 0 ,0.5, 1.0, 1.5....9.5
e = np.arange(0, 10, 0.5)

#np.linspace(0, 1, 100) will create exactly 100 evenly spaced values between 0 and 1
#diffrent from arange because it will give you exactly 100 values between 0 and 1 even if the step size is not exactly 0.01
#useful for smooth curve plotting
f = np.linspace(0, 1, 100)

#np.eye(4) will make a identity matrix of size 4 by 4 where 1 on diagonal and rest 0
# in maths when u multiply any matrix with it ,it returns the same one back
g = np.eye(4) 

#.shape will give u the diemnsion of the array
#d.shape will return (3, 4) which means 3 rows and 4 columns
print("Shape of d:" , d.shape) 

#.dtype willl give the type of number sstored
#usulaly we have float64 ie 64 bit floating point numbers for ML 
print("Data type:" , d.dtype)

#.size will give the total number of elements in the array
#for d it will be 3*4 = 12
print("total elements in d:" , d.size)

print()
print("Identity matrix:")
#printing g shows u the identity matrix of size 4 by 4
print(g)






Shape of d: (3, 4)
Data type: float64
total elements in d: 12

Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
#Cell 2 broadcasting

#3 by 3 matrix - we use nested list,
#one list per row
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])  #shape is 3x3

#simple 1d array
b =np.array([10, 20, 30]) #shape is 3

#when we add then numpy broadcasts them acrpss every row of a
c = a + b
#Row 0: [1+10, 2+20, 3+30] = [11, 22, 33]
#Row 1: [4+10, 5+20, 6+30] = [14, 25, 36]
#Row 2: [7+10, 8+20, 9+30] = [17, 28, 39]

result = a + b
print("Matrix + vector (brqoadcasting):")
print(result)
print()

#weights shape: (4, 3) - 4 output neurons and 3 input features
#this means that 4 neurons are looking at 3 features each
weights = np.random.randn(4, 3)

#input shape: (3,) - 3 features of one data sample
input = np.random.randn(3)

#bias shape: (4,) one bias value per output neutron
bias = np.random.randn(4)


# @ is the matrix  multiplication operator in python (added in python 3.5)
# weight @ inputs does the dot product of each row of weights with inputs
# then we add bias  it broadcasts automatically across the 4 outputs
#result shape  (4,) one output per neutron
output = weights @ input + bias

print ("neural network forward pass :")
print("weights shape:", weights.shape)  #(4, 3)
print("input shape:", input.shape)    #(3,)
print("bias shape:", bias.shape)      #(4,) - 4 neutron outputs
print("output :", np.round(output, 4))  #(4,)




Matrix + vector (brqoadcasting):
[[11 22 33]
 [14 25 36]
 [17 28 39]]

neural network forward pass :
weights shape: (4, 3)
input shape: (3,)
bias shape: (4,)
output : [-3.5937 -0.1341  1.3804  0.7019]


In [11]:
#Cell 3 - why numpy exsists (speed demonstration)
#we import. time to measure how long operation take import time
import time

#we will multiply 1 million numbers together 2 ways
size = 1_000_000   #python allows underscores in numbers for readability

# METHOD 1 - using python lists with a  loop
a = list(range(size))   #python list of integers from 0 to 999,999
b = list(range(size))   #another list of same size

#time.time() gives us the current time in seconds since epoch
start = time.time()

#list comprehension : for each index i , multiply a[i] and b[i]
#python will have to fetch each element one by one and multiply them
c_slow = [a[i] * b[i] for i in range(size)]

#calculate how long it took by subtracting start time from current time
slow_time = time.time() - start

#method 2 ; numpy vectoized operation
#np.arange creates the array - dtype=np.float64 specifies that we want 64 bit floating point numbers
a_np = np.arange(size, dtype=np.float64)
b_np = np.arange(size, dtype=np.float64)
start = time.time()
 
 #the * operator on numpy multiplies all the elemnts simultaneously 
 #numpy calls underlying c code under the hood which is much faster than python loops
c_fast = a_np * b_np

fast_time = time.time() - start

print(f"Python loop:      {slow_time:.4f} seconds")
print(f"NumPy vectorised: {fast_time:.4f} seconds")
print(f"NumPy is {slow_time/fast_time:.0f}x faster")
print()
print("RULE: Never loop over array elements in Python for ML work.")
print("Always express operations as NumPy array operations.")
print("This rule applies to pandas, PyTorch, and every other ML library.")


Python loop:      0.0537 seconds
NumPy vectorised: 0.0010 seconds
NumPy is 53x faster

RULE: Never loop over array elements in Python for ML work.
Always express operations as NumPy array operations.
This rule applies to pandas, PyTorch, and every other ML library.
